name: azure-managed-identity-config pipeline
pr:
  branches:
    include:
      - master

jobs:
  - job: Validate
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - template: setup-pulumi.yaml
      - script: |
          export PATH=~/.pulumi/bin:${PATH}

          pulumi preview
        env:
          ARM_CLIENT_ID: $(umi-arm-client-id)
          ARM_CLIENT_SECRET: $(umi-arm-client-secret)
          ARM_SUBSCRIPTION_ID: $(umi-arm-subscription-id)
          ARM_TENANT_ID: $(umi-arm-tenant-id)
          ENV: $(env)
        displayName: 'Pulumi preview'

  - job: Release_RPETEMP
    pool:
      vmImage: 'Ubuntu 16.04'
    condition: >
      and(
          succeeded(),
          eq(variables['Build.SourceBranch'], 'refs/heads/master')
        )
    dependsOn: Validate
    steps:
      - template: setup-pulumi.yaml
        parameters:
          state_store_subscription_id: 'a5453007-c32b-4336-9c79-3f643d817aea'
          state_store_account_name: 'rpetemptfstate'
          state_store_container_name: 'rpetemp'
          service_connection: 'azurerm_rpetemp_mi'
      - template: release-pulumi.yaml
        parameters:
          state_store_subscription_id: 'a5453007-c32b-4336-9c79-3f643d817aea'
          state_store_account_name: 'rpetemptfstate'
          state_store_container_name: 'rpetemp'
          service_connection: 'azurerm_rpetemp_mi'
