name: azure-managed-identity-config pipeline
trigger:
  branches:
    include:
      - refs/tags/*
pr:
  branches:
    include:
      - master

jobs:
  - job: Validate
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 'v11.14.0'
        displayName: 'Install Node.js'
      - script: |
          curl -fsSL https://get.pulumi.com | sh

          export PATH=~/.pulumi/bin:${PATH}
          pulumi plugin install resource azure v0.17.4
          pulumi login --local

          pulumi stack init aad
        displayName: 'Install Pulumi'
      - task: AzureCLI@1
        inputs:
          azureSubscription: azurerm_rpetemp_mi
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob download -f ~/.pulumi/stacks/aad.json \
              --container-name rpetemp --name pulumi/stacks/aad.json \
              --account-name rpetemptfstate \
              --subscription a5453007-c32b-4336-9c79-3f643d817aea
        displayName: 'Download pulumi state'
      - task: Npm@1
        inputs:
          command: 'install'
      - script: |
          export PATH=~/.pulumi/bin:${PATH}

          pulumi preview
        env:
          ARM_CLIENT_ID: $(umi-arm-client-id)
          ARM_CLIENT_SECRET: $(umi-arm-client-secret)
          ARM_SUBSCRIPTION_ID: $(umi-arm-tenant-id)
          ARM_TENANT_ID: $(umi-arm-subscription-id)
          ENV: $(env)
        displayName: 'Pulumi preview'
